# Linear Operators

Finite dimensional linear operators allow matrix algebra without explicitly constructing a full representation. Instead it suffices to define a matrix-vector product and a shape attribute. This avoids unnecessary memory usage and can often be more convenient to derive.

## Sparse Arrays

In [6]:
import numpy as np
import scipy.sparse
from probnum.linalg.linear_operators import MatrixMult, Identity

n = 10
mat = scipy.sparse.rand(m=n, n=n, density=0.1)
A = MatrixMult(A=mat)
print(A.todense())

[[0.         0.         0.         0.         0.         0.
  0.         0.73046692 0.         0.        ]
 [0.         0.         0.         0.         0.         0.
  0.         0.         0.         0.        ]
 [0.         0.         0.         0.18262133 0.         0.
  0.13798833 0.         0.         0.        ]
 [0.85706046 0.         0.         0.         0.         0.06490056
  0.         0.         0.         0.45434562]
 [0.         0.         0.         0.         0.         0.
  0.28805377 0.         0.         0.        ]
 [0.         0.         0.         0.         0.         0.
  0.         0.         0.         0.        ]
 [0.         0.         0.         0.         0.         0.
  0.62799748 0.         0.         0.        ]
 [0.         0.         0.         0.         0.         0.
  0.         0.         0.82270437 0.        ]
 [0.         0.         0.         0.83781768 0.         0.
  0.         0.         0.         0.        ]
 [0.         0.         0.   

## Basic Arithmetic

In [7]:
Id = Identity(shape=n)
B = A + Id
print(B.todense())

AttributeError: '_SumLinearOperator' object has no attribute 'todense'

## The Kronecker Product

In [8]:
from probnum.linalg.linear_operators import Kronecker, SymmetricKronecker

# Kronecker Product
A = np.array([[5, 1], [2, 10]])
W = Kronecker(A=A, B=A)
print(W.todense())

# Symmetric Kronecker Product
#Ws = SymmetricKronecker(A=A, B=B)

[[ 25.   5.   5.   1.]
 [ 10.  50.   2.  10.]
 [ 10.   2.  50.  10.]
 [  4.  20.  20. 100.]]


## Linear Operators and Linear Solvers

Many methods implemented in `probnum.linalg` can also take `LinearOperators` as inputs.