# Random Variables

Below we illustrate some basic usage of random variables and linear operators in `probnum`. We begin by creating random variables, the primary in- and outputs of probabilistic numerical methods.

## Univariate Random Variables

Instantiate and manipulate random variables and linear operators.

In [1]:
import numpy as np
from probnum.probability import RandomVariable, Normal

# Seed
np.random.seed(42)

# Gaussian random variable
X = RandomVariable(distribution=Normal(mean=0.5, cov=1))

# Arithmetic operations between scalars and random variables
Y = 2 * X - 1
print(Y)

<() RandomVariable with dtype=<class 'float'>>


In [2]:
# Samples / realizations
Y.sample(size=(2, 3))

array([[ 0.99342831, -0.2765286 ,  1.29537708],
       [ 3.04605971, -0.46830675, -0.46827391]])

## Arithmetic Operations

Add, multiply, ... scalars and vectors with random variables or apply linear transformations.

### Vectors and Matrices

In [10]:
A = np.array([[1, 2], 
              [3, 2]])
X = RandomVariable(distribution=Normal(mean=np.array([1, 2]), cov=np.array([[2, 0], 
                                                                            [0, 5]])))
Y = A @ X - np.array([1, 2])
print(Y)

<(2,) RandomVariable with dtype=<class 'float'>>

In [4]:
Y.sample(size=3)

array([[-3.12837959, -1.8451091 ],
       [ 6.37960911, 10.39528139],
       [ 7.70884096,  9.35659646]])

### Linear Operators

In [5]:
from probnum.linalg import aslinop

# Linear operators applied to random variables
A = aslinop(np.array([[1, 2], 
                      [3, 4]]))
Y = A @ X
print(Y)

<(2,) RandomVariable with dtype=<class 'float'>>


In [6]:
Y.sample(size=(3,2))

array([[[ 4.87290569,  8.13409903],
        [13.33422164, 27.93200714]],

       [[ 9.55660383, 21.10082663],
        [ 9.97114444, 19.63827357]],

       [[-1.71353421, -3.56030951],
        [ 5.43044696,  9.98072378]]])

## Matrix-variate Random Variables

In [ ]:
# Matrix-variate normal distribution

## Linear Operators as Random Variables

In [4]:
# Linear operators _as_ random variables